# Generated by Django 6.0.2 on 2026-02-19 22:12

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='accounts_cu_school__13d8d9_idx',
            old_name='accounts_cu_school_role_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='accounts_cu_email_5ce40b_idx',
            old_name='accounts_cu_email_idx',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='school',
            name='description',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Courte biographie ou description', max_length=500, null=True, verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Indique si le compte est suspendu', verbose_name='Compte suspendu'),
        ),
        migrations.AddField(
            model_name='school',
            name='director_name',
            field=models.CharField(blank=True, help_text='Nom du directeur ou responsable principal', max_length=255, null=True, verbose_name='Nom du directeur'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text="Photo de profil de l'utilisateur", null=True, upload_to='users/profiles/%Y/%m/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo de l'établissement", null=True, upload_to='schools/logos/%Y/%m/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='school',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, help_text="Adresse du site web de l'école", null=True, verbose_name='Site web'),
        ),
    ]
