# Generated by Django 4.2.28 on 2026-03-03 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_terms_grades'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='class',
            new_name='academics_c_school__859e2b_idx',
            old_name='academics_c_school_idx',
        ),
        migrations.RenameIndex(
            model_name='class',
            new_name='academics_c_school__6da513_idx',
            old_name='academics_c_school_year_idx',
        ),
        migrations.RenameIndex(
            model_name='grade',
            new_name='academics_g_student_846a4f_idx',
            old_name='academics_g_student_term_idx',
        ),
        migrations.RenameIndex(
            model_name='grade',
            new_name='academics_g_school__b2b580_idx',
            old_name='academics_g_school_term_idx',
        ),
        migrations.RenameIndex(
            model_name='subject',
            new_name='academics_s_school__c27572_idx',
            old_name='academics_s_school_code_idx',
        ),
        migrations.RenameIndex(
            model_name='subject',
            new_name='academics_s_school__ea36ae_idx',
            old_name='academics_s_school_active_idx',
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2036)]),
        ),
    ]
