# Generated by Django 6.0.2 on 2026-02-19 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('view_student_reports', 'Peut voir les rapports des élèves'), ('export_students', 'Peut exporter les élèves')], 'verbose_name': 'Élève', 'verbose_name_plural': 'Élèves'},
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_school__e97f55_idx',
            old_name='students_st_school_grade_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_school__332118_idx',
            old_name='students_st_school_status_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_student_e7126a_idx',
            old_name='students_st_student_id_idx',
        ),
    ]
